-- ============================================
-- TABLE: plans (5 rows)
-- ============================================
INSERT INTO plans (id, name, max_members, price_monthly, price_yearly, features, is_popular, code, description, is_public, is_custom, is_white_label, sort_order, max_admins, capabilities, tagline, max_tags, policies, updated_at, updated_by) VALUES
('enterprise', 'Grand Compte', NULL, NULL, NULL, '["Membres illimités", "Configuration personnalisée", "Connexions spécifiques", "Sécurité renforcée", "Responsable de compte dédié", "Accompagnement & formation", "Support 24/7"]', false, 'ENTREPRISE_CUSTOM', 'Solution sur-mesure pour réseaux nationaux ou internationaux', true, true, false, 4, NULL, '{"admins": {"max": 999}, "members": {"max": null}, "support": "dedicated", "features": {"tags": true, "qrCard": true, "analytics": "advanced", "messaging": true, "dataExport": true, "cotisations": true, "integrations": true, "targetedContent": true, "eventRegistration": true, "sectionsUnlimited": true}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('free', 'Free Starter', 20, 0, 0, '["Jusqu''à 50 membres", "Cartes de membre digitales", "Fil d''actualités", "Événements simples", "1 administrateur", "Support par email"]', false, 'STARTER_FREE', 'Découvrir et tester la plateforme', true, false, false, 1, 1, '{"admins": {"max": 1}, "members": {"max": 20}, "support": "standard", "features": {"tags": false, "qrCard": false, "analytics": "none", "messaging": false, "dataExport": false, "cotisations": true, "integrations": false, "targetedContent": false, "eventRegistration": false, "sectionsUnlimited": false}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('growth', 'Communauté Plus', 100, 990, 9900, '["Jusqu''à 200 membres", "Cartes de membre avec QR code", "Gestion des cotisations", "Événements avec inscriptions", "Messagerie membres ↔ admins", "Statistiques essentielles", "Jusqu''à 3 administrateurs", "Support prioritaire"]', true, 'COMMUNAUTE_STANDARD', 'Animer efficacement une communauté structurée', true, false, false, 2, 2, '{"admins": {"max": 3}, "members": {"max": 100}, "support": "priority", "features": {"tags": false, "qrCard": true, "analytics": "basic", "messaging": true, "dataExport": false, "cotisations": true, "integrations": false, "targetedContent": false, "eventRegistration": true, "sectionsUnlimited": false}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('scale', 'Communauté Pro', 250, 2900, 29000, '["Jusqu''à 1 000 membres", "Gestion d''équipe (rôles & permissions)", "Sections / régions illimitées", "Tags membres + contenus ciblés", "Statistiques avancées", "Export de données", "Connexion à vos outils existants", "Jusqu''à 10 administrateurs", "Support prioritaire étendu"]', false, 'COMMUNAUTE_PRO', 'Piloter et développer une organisation', true, false, false, 3, 5, '{"admins": {"max": 10}, "members": {"max": 250}, "support": "priority", "features": {"tags": true, "qrCard": true, "analytics": "advanced", "messaging": true, "dataExport": true, "cotisations": true, "integrations": true, "targetedContent": true, "eventRegistration": true, "sectionsUnlimited": true}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('whitelabel', 'Koomy White Label', NULL, NULL, 490000, '["Plateforme en marque blanche", "Nom de domaine personnalisé", "Branding complet", "App mobile personnalisée", "Membres illimités", "Toutes les fonctionnalités Pro", "Support dédié premium", "Maintenance incluse"]', false, 'WHITE_LABEL', 'Votre propre plateforme à vos couleurs', false, false, true, 5, NULL, '{"admins": {"max": 999}, "members": {"max": null}, "support": "dedicated", "features": {"tags": true, "qrCard": true, "analytics": "advanced", "messaging": true, "dataExport": true, "cotisations": true, "integrations": true, "targetedContent": true, "eventRegistration": true, "sectionsUnlimited": true}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL);
