-- ============================================
-- POC DATABASE - BUSINESS DATA MIGRATION
-- Generated: 2026-01-29 (COMPLETE)
-- ============================================
-- STEP 1: Create schema first using drizzle-kit push
-- DATABASE_URL="postgresql://neondb_owner:npg_S3rzHMgTX7qc@ep-sweet-rain-ahdi5g25-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require" npx drizzle-kit push
-- 
-- STEP 2: Then run this SQL file to insert business data
-- ============================================

-- ============================================
-- TABLE: plans (5 rows)
-- ============================================
INSERT INTO plans (id, name, max_members, price_monthly, price_yearly, features, is_popular, code, description, is_public, is_custom, is_white_label, sort_order, max_admins, capabilities, tagline, max_tags, policies, updated_at, updated_by) VALUES
('enterprise', 'Grand Compte', NULL, NULL, NULL, '["Membres illimités", "Configuration personnalisée", "Connexions spécifiques", "Sécurité renforcée", "Responsable de compte dédié", "Accompagnement & formation", "Support 24/7"]', false, 'ENTREPRISE_CUSTOM', 'Solution sur-mesure pour réseaux nationaux ou internationaux', true, true, false, 4, NULL, '{"admins": {"max": 999}, "members": {"max": null}, "support": "dedicated", "features": {"tags": true, "qrCard": true, "analytics": "advanced", "messaging": true, "dataExport": true, "cotisations": true, "integrations": true, "targetedContent": true, "eventRegistration": true, "sectionsUnlimited": true}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('free', 'Free Starter', 20, 0, 0, '["Jusqu''à 50 membres", "Cartes de membre digitales", "Fil d''actualités", "Événements simples", "1 administrateur", "Support par email"]', false, 'STARTER_FREE', 'Découvrir et tester la plateforme', true, false, false, 1, 1, '{"admins": {"max": 1}, "members": {"max": 20}, "support": "standard", "features": {"tags": false, "qrCard": false, "analytics": "none", "messaging": false, "dataExport": false, "cotisations": true, "integrations": false, "targetedContent": false, "eventRegistration": false, "sectionsUnlimited": false}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('growth', 'Communauté Plus', 100, 990, 9900, '["Jusqu''à 200 membres", "Cartes de membre avec QR code", "Gestion des cotisations", "Événements avec inscriptions", "Messagerie membres ↔ admins", "Statistiques essentielles", "Jusqu''à 3 administrateurs", "Support prioritaire"]', true, 'COMMUNAUTE_STANDARD', 'Animer efficacement une communauté structurée', true, false, false, 2, 2, '{"admins": {"max": 3}, "members": {"max": 100}, "support": "priority", "features": {"tags": false, "qrCard": true, "analytics": "basic", "messaging": true, "dataExport": false, "cotisations": true, "integrations": false, "targetedContent": false, "eventRegistration": true, "sectionsUnlimited": false}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('scale', 'Communauté Pro', 250, 2900, 29000, '["Jusqu''à 1 000 membres", "Gestion d''équipe (rôles & permissions)", "Sections / régions illimitées", "Tags membres + contenus ciblés", "Statistiques avancées", "Export de données", "Connexion à vos outils existants", "Jusqu''à 10 administrateurs", "Support prioritaire étendu"]', false, 'COMMUNAUTE_PRO', 'Piloter et développer une organisation', true, false, false, 3, 5, '{"admins": {"max": 10}, "members": {"max": 250}, "support": "priority", "features": {"tags": true, "qrCard": true, "analytics": "advanced", "messaging": true, "dataExport": true, "cotisations": true, "integrations": true, "targetedContent": true, "eventRegistration": true, "sectionsUnlimited": true}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL),
('whitelabel', 'Koomy White Label', NULL, NULL, 490000, '["Plateforme en marque blanche", "Nom de domaine personnalisé", "Branding complet", "App mobile personnalisée", "Membres illimités", "Toutes les fonctionnalités Pro", "Support dédié premium", "Maintenance incluse"]', false, 'WHITE_LABEL', 'Votre propre plateforme à vos couleurs', false, false, true, 5, NULL, '{"admins": {"max": 999}, "members": {"max": null}, "support": "dedicated", "features": {"tags": true, "qrCard": true, "analytics": "advanced", "messaging": true, "dataExport": true, "cotisations": true, "integrations": true, "targetedContent": true, "eventRegistration": true, "sectionsUnlimited": true}}', NULL, NULL, NULL, '2026-01-26 16:10:50.73929', NULL);

-- ============================================
-- TABLE: faqs (6 rows)
-- ============================================
INSERT INTO faqs (id, question, answer, category, target_role) VALUES
('376a83dd-19dc-434a-9bf0-890c8cfc7dbe', 'How do I access my digital membership card?', 'Your digital membership card is available in the ''Membership'' section of the mobile app. It includes a QR code that can be scanned for verification.', 'Membership', 'member'),
('5d975ea5-0c8c-4fb2-99cd-1d156bc2c311', 'How do I add new members to my community?', 'Navigate to the Members section in the admin portal, click ''Add Member'', and fill in their details. They will receive an invitation email to set up their account.', 'Member Management', 'admin'),
('6b62a380-c9af-48e2-a8af-f43c05b13886', 'How can I update my contribution status?', 'Contact your community administrator or use the payment section in your profile to update contribution information.', 'Contributions', 'member'),
('72bd7e5d-b472-4cd4-a737-938e0cb1db6e', 'Can I publish news to specific sections only?', 'Yes! When creating news, select ''Local'' scope and choose the target section. Only members of that section will see the article.', 'Content Management', 'admin'),
('86bc5f65-261c-47c2-be1c-f71611bcf648', 'How do I upgrade my community''s subscription plan?', 'Go to Settings > Subscription in your admin portal. Select the desired plan and complete the payment process.', 'Billing', 'admin'),
('8bf7ffaa-4b51-4dfd-a70b-d15f3ae40471', 'How do I contact my community administrators?', 'Use the Messages tab in the app to send direct messages to administrators or delegates in your community.', 'Support', 'member');

-- ============================================
-- TABLE: email_templates (9 rows)
-- ============================================
INSERT INTO email_templates (id, type, subject, html, updated_at) VALUES
('1816e258-ff52-43cd-8d39-1d35a4a402e7', 'invite_delegate', 'Invitation à rejoindre {{communityName}} en tant que délégué', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Invitation à rejoindre {{communityName}}</h1><p>Bonjour {{name}},</p><p>{{adminName}} vous invite à rejoindre la communauté <strong>{{communityName}}</strong> en tant que <strong>{{role}}</strong>.</p><p>Cliquez sur le bouton ci-dessous pour activer votre compte :</p><p><a href="{{activationUrl}}" style="display: inline-block; background-color: #7c3aed; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Activer mon compte</a></p><p style="margin-top: 30px; color: #666; font-size: 12px;">Cet email a été envoyé par Koomy.</p></div></body></html>', '2025-12-03 12:39:51.819486'),
('42cd1763-03f2-47ab-ac38-6602beb10e94', 'verify_email', 'Vérifiez votre adresse email', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Vérifiez votre email</h1><p>Bonjour {{name}},</p><p>Votre code de vérification est :</p><p style="font-size: 32px; font-weight: bold; color: #7c3aed; text-align: center; letter-spacing: 4px;">{{codeVerification}}</p><p>Ou cliquez sur le bouton ci-dessous :</p><p><a href="{{activateUrl}}" style="display: inline-block; background-color: #7c3aed; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Vérifier mon email</a></p><p style="margin-top: 30px; color: #666; font-size: 12px;">Ce code expire dans 15 minutes.</p></div></body></html>', '2025-12-03 12:39:51.819486'),
('69a16e37-2b1e-4dd4-b21a-cd371882d612', 'welcome_community_admin', 'Bienvenue sur Koomy - {{communityName}}', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Bienvenue sur Koomy, {{name}} !</h1><p>Félicitations ! Votre communauté <strong>{{communityName}}</strong> a été créée avec succès.</p><p>Votre code communauté : <strong style="font-size: 18px; color: #7c3aed;">{{code}}</strong></p><p>Connectez-vous dès maintenant pour commencer à gérer votre communauté :</p><p><a href="{{loginUrl}}" style="display: inline-block; background-color: #7c3aed; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Accéder à mon espace</a></p><p style="margin-top: 30px; color: #666; font-size: 12px;">Cet email a été envoyé par Koomy.</p></div></body></html>', '2025-12-03 12:39:51.819486'),
('6ea19d49-a861-41f9-9b06-7568706b1a73', 'reset_password', 'Réinitialisation de votre mot de passe Koomy', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Réinitialisation du mot de passe</h1><p>Bonjour {{name}},</p><p>Vous avez demandé à réinitialiser votre mot de passe.</p><p>Cliquez sur le bouton ci-dessous pour définir un nouveau mot de passe :</p><p><a href="{{resetUrl}}" style="display: inline-block; background-color: #7c3aed; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Réinitialiser mon mot de passe</a></p><p style="color: #666;">Ce lien expire dans 1 heure.</p><p style="margin-top: 30px; color: #666; font-size: 12px;">Si vous n avez pas demandé cette réinitialisation, ignorez ce message.</p></div></body></html>', '2025-12-03 12:39:51.819486'),
('7ffd70a1-7999-498c-9bb4-4347646c782a', 'invite_member', 'Bienvenue chez {{communityName}}', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Bienvenue chez {{communityName}} !</h1><p>Bonjour {{name}},</p><p>Vous avez été ajouté(e) comme membre de <strong>{{communityName}}</strong>.</p><p>Votre code membre : <strong style="font-size: 18px; color: #7c3aed;">{{codeMembre}}</strong></p><p>Téléchargez l application Koomy et utilisez ce code pour accéder à votre espace membre :</p><p><a href="{{activationUrl}}" style="display: inline-block; background-color: #7c3aed; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Activer mon compte</a></p><p style="margin-top: 30px; color: #666; font-size: 12px;">Cet email a été envoyé par Koomy.</p></div></body></html>', '2026-01-08 20:37:58.212'),
('842813b4-0c6f-482e-86b4-51972631202d', 'new_collection', 'Nouvelle collecte : {{title}}', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Nouvelle collecte</h1><p>Une nouvelle collecte a été lancée dans <strong>{{communityName}}</strong> :</p><div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;"><h2 style="margin: 0 0 10px 0; color: #7c3aed;">{{title}}</h2><p style="margin: 5px 0; color: #666;"><strong>Montant :</strong> {{amount}} EUR</p><p style="margin: 5px 0; color: #666;"><strong>Date limite :</strong> {{deadline}}</p></div><p style="margin-top: 30px; color: #666; font-size: 12px;">Cet email a été envoyé par Koomy.</p></div></body></html>', '2025-12-03 12:39:51.819486'),
('e91e23c7-5acb-4953-b637-1099974ddfa0', 'new_event', 'Nouvel événement : {{title}}', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Nouvel événement</h1><p>Un nouvel événement a été créé dans <strong>{{communityName}}</strong> :</p><div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;"><h2 style="margin: 0 0 10px 0; color: #7c3aed;">{{title}}</h2><p style="margin: 0; color: #666;"><strong>Date :</strong> {{date}}</p></div><p style="margin-top: 30px; color: #666; font-size: 12px;">Cet email a été envoyé par Koomy.</p></div></body></html>', '2025-12-03 12:39:51.819486'),
('4220c082-c0bb-42bf-bfca-a272b52f8d3e', 'message_to_admin', 'Nouveau message de {{memberName}}', '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><h1 style="color: #7c3aed;">Nouveau message reçu</h1><p>Vous avez reçu un nouveau message de <strong>{{memberName}}</strong> :</p><div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;"><p style="margin: 0 0 10px 0;"><strong>Sujet :</strong> {{subject}}</p><p style="margin: 0; white-space: pre-wrap;">{{message}}</p></div><p style="margin-top: 30px; color: #666; font-size: 12px;">Cet email a été envoyé par Koomy.</p></div></body></html>', '2025-12-03 12:39:51.819486'),
('2af9b9dd-1f3b-4e1b-8de3-9f6ed3924485', 'owner_admin_credentials', 'Vos identifiants d''administrateur pour {{communityName}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin: 0; padding: 0; font-family: Arial, sans-serif; background-color: #f5f5f5;"><div style="max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%); padding: 30px; border-radius: 10px 10px 0 0;"><h1 style="color: white; margin: 0; font-size: 24px;">Vos identifiants administrateur</h1></div><div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);"><p style="color: #333; font-size: 16px; line-height: 1.6;">Bonjour <strong>{{displayName}}</strong>,</p><p style="color: #333; font-size: 16px; line-height: 1.6;">Vous avez été désigné comme <strong>administrateur propriétaire</strong> de la communauté <strong>{{communityName}}</strong>.</p><div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 20px 0;"><h3 style="margin: 0 0 15px 0; color: #1e293b;">Vos identifiants de connexion :</h3><p style="margin: 8px 0; color: #475569;"><strong>Email :</strong> {{email}}</p><p style="margin: 8px 0; color: #475569;"><strong>Mot de passe :</strong> <code style="background: #fef3c7; padding: 2px 6px; border-radius: 4px;">{{password}}</code></p></div><p style="color: #ef4444; font-size: 14px; line-height: 1.6;"><strong>Important :</strong> Pour des raisons de sécurité, nous vous recommandons de changer ce mot de passe dès votre première connexion.</p><div style="text-align: center; margin: 30px 0;"><a href="{{loginUrl}}" style="display: inline-block; background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%); color: white; padding: 14px 28px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px;">Se connecter</a></div><p style="color: #64748b; font-size: 14px; line-height: 1.6;">En tant qu administrateur propriétaire, vous avez accès à toutes les fonctionnalités de gestion de votre communauté.</p></div><div style="text-align: center; padding: 20px; color: #94a3b8; font-size: 12px;"><p>Cet email a été envoyé automatiquement par Koomy.</p></div></div></body></html>', '2025-12-05 12:08:24.632716');

-- ============================================
-- SUMMARY
-- ============================================
-- plans: 5 rows
-- faqs: 6 rows
-- email_templates: 9 rows
-- TOTAL: 20 rows of platform business data
-- ============================================
