-- STEP 2: Communities columns (execute second)
ALTER TABLE communities ADD COLUMN IF NOT EXISTS max_admins_default INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS contract_admin_limit INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS billing_status billing_status DEFAULT 'active';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS white_label BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS white_label_tier white_label_tier;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS auth_mode auth_mode DEFAULT 'FIREBASE_ONLY';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS billing_mode billing_mode DEFAULT 'self_service';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS setup_fee_amount_cents INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS setup_fee_currency TEXT DEFAULT 'EUR';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS setup_fee_invoice_ref TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS maintenance_amount_year_cents INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS maintenance_currency TEXT DEFAULT 'EUR';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS maintenance_next_billing_date TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS maintenance_status maintenance_status;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS internal_notes TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS brand_config JSONB;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS branding_logo_path TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS branding_icon_path TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS branding_splash_path TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS branding_primary_color TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS branding_secondary_color TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS custom_domain TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS web_app_url TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS android_store_url TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS ios_store_url TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS white_label_included_members INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS white_label_max_members_soft_limit INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS white_label_additional_fee_per_member_cents INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS account_type account_type DEFAULT 'STANDARD';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS distribution_channels JSONB;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS contract_member_limit INTEGER;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS contract_member_alert_threshold INTEGER DEFAULT 90;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS member_id_prefix TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS member_id_counter INTEGER DEFAULT 0;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS saas_client_status saas_client_status DEFAULT 'ACTIVE';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS saas_status_changed_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS unpaid_since TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS terminated_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS purge_scheduled_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS purge_status purge_status;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS purge_executed_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS self_enrollment_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS self_enrollment_channel self_enrollment_channel DEFAULT 'OFFLINE';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS self_enrollment_mode self_enrollment_mode DEFAULT 'OPEN';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS self_enrollment_slug TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS self_enrollment_eligible_plans JSONB;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS self_enrollment_required_fields JSONB;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS self_enrollment_sections_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS member_join_code TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS cgv_accepted_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS cgv_version TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS newsletter_opt_in BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS full_access_granted_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS full_access_expires_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS full_access_reason TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS full_access_granted_by VARCHAR(50);
ALTER TABLE communities ADD COLUMN IF NOT EXISTS stripe_connect_account_id TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS stripe_connect_status stripe_connect_status DEFAULT 'NOT_CONNECTED';
ALTER TABLE communities ADD COLUMN IF NOT EXISTS stripe_connect_charges_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS stripe_connect_payouts_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS stripe_connect_details_submitted BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS stripe_connect_last_sync_at TIMESTAMP;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS payments_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS platform_fee_percent INTEGER DEFAULT 2;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS connect_fee_fixed_cents INTEGER DEFAULT 0;

SELECT column_name FROM information_schema.columns WHERE table_name = 'communities' AND column_name IN ('max_admins_default', 'contract_admin_limit');
