-- STEP 1: ENUMS (execute first)
DO $$ BEGIN CREATE TYPE subscription_status AS ENUM ('trialing', 'active', 'past_due', 'canceled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE member_status AS ENUM ('active', 'expired', 'suspended'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE contribution_status AS ENUM ('up_to_date', 'expired', 'pending', 'late'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE admin_role AS ENUM ('super_admin', 'support_admin', 'finance_admin', 'content_admin', 'admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE user_global_role AS ENUM ('platform_super_admin', 'platform_ops', 'platform_support', 'platform_finance', 'platform_commercial', 'platform_readonly'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE billing_period AS ENUM ('one_time', 'monthly', 'yearly'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE billing_mode AS ENUM ('self_service', 'manual_contract'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE white_label_tier AS ENUM ('basic', 'standard', 'premium'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE maintenance_status AS ENUM ('active', 'pending', 'late', 'stopped'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE stripe_connect_status AS ENUM ('NOT_CONNECTED', 'ONBOARDING_REQUIRED', 'PENDING_REVIEW', 'RESTRICTED', 'ACTIVE', 'DISCONNECTED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE account_type AS ENUM ('STANDARD', 'GRAND_COMPTE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE saas_client_status AS ENUM ('ACTIVE', 'IMPAYE_1', 'IMPAYE_2', 'SUSPENDU', 'RESILIE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE purge_status AS ENUM ('scheduled', 'canceled_by_reactivation', 'executed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE self_enrollment_channel AS ENUM ('OFFLINE', 'ONLINE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE self_enrollment_mode AS ENUM ('OPEN', 'CLOSED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth_mode AS ENUM ('FIREBASE_ONLY', 'LEGACY_ONLY'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE identity_provider AS ENUM ('FIREBASE', 'LEGACY_KOOMY'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE membership_billing_type AS ENUM ('one_time', 'annual'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE membership_plan_type AS ENUM ('FIXED_PERIOD', 'ROLLING_DURATION'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE fixed_period_type AS ENUM ('CALENDAR_YEAR', 'SEASON'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE membership_payment_status AS ENUM ('free', 'due', 'paid'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE salutation_enum AS ENUM ('M', 'Mme', 'Autre'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE ticket_status AS ENUM ('open', 'in_progress', 'resolved', 'closed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE ticket_priority AS ENUM ('low', 'medium', 'high'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE news_status AS ENUM ('draft', 'published'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE scope AS ENUM ('national', 'local'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_status AS ENUM ('pending', 'completed', 'failed', 'refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_request_status AS ENUM ('pending', 'paid', 'expired', 'cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE email_type AS ENUM ('welcome_community_admin', 'invite_delegate', 'invite_member', 'reset_password', 'verify_email', 'new_event', 'new_collection', 'collection_contribution_thanks', 'message_to_admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE collection_status AS ENUM ('open', 'closed', 'canceled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE transaction_type AS ENUM ('subscription', 'membership', 'collection'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE transaction_status AS ENUM ('pending', 'succeeded', 'failed', 'refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE tag_type AS ENUM ('user', 'content', 'hybrid'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_visibility_mode AS ENUM ('ALL', 'SECTION', 'TAGS'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_rsvp_mode AS ENUM ('NONE', 'OPTIONAL', 'REQUIRED', 'APPROVAL'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_status AS ENUM ('DRAFT', 'PUBLISHED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_registration_status AS ENUM ('GOING', 'NOT_GOING', 'WAITLIST', 'PENDING', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_payment_status AS ENUM ('NONE', 'PENDING', 'PAID', 'FAILED', 'REFUNDED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE attendance_source AS ENUM ('QR_SCAN', 'MANUAL'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE saas_transition_reason AS ENUM ('PAYMENT_FAILED', 'PAYMENT_SUCCEEDED', 'DELAY_EXPIRED', 'MANUAL'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE enrollment_request_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'CONVERTED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE audit_action_enum AS ENUM ('login', 'logout', 'session_expired', 'session_renewed', 'create_user', 'update_user', 'delete_user', 'update_role', 'create_community', 'update_community', 'delete_community', 'create_plan', 'update_plan', 'delete_plan', 'grant_full_access', 'revoke_full_access', 'stripe_connect_enabled', 'stripe_connect_disabled', 'billing_mode_changed', 'white_label_enabled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

SELECT typname FROM pg_type WHERE typtype = 'e' ORDER BY typname;
